name: Data Preprocessing

on:
  push:
    branches:
      - main  # Run the workflow when there's a push to the main branch
  pull_request:
    branches:
      - main  # Optionally, run on pull requests too

jobs:
  preprocess:
    runs-on: ubuntu-latest  # Set up the environment (Linux-based in this case)

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'  # Specify your Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Run Data Preprocessing
      run: |
        python preprocess_data.py  # Replace with your Python script

    - name: Upload plot artifact
      uses: actions/upload-artifact@v4
      with:
        name: nifty-plots
        path: ./your_plot.png  # The path where your plot is saved (adjust as needed)
