name: Demo pyhton workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Setting up python
      uses: actions/setup-python@v4
      with: 
        python-version: ${{ matrix.python-version }} 
    - name: Installing dependencies for Python project
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [-f requirement.txt ]; then pip install -r requirement.txt; fi
    - name: Linting Python project using flake8
      run: |
        flake8 . --count --select=E8,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Testing the python project using pytest
    run: |
      pip install pytest
      pip install pytest-cov
      pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
